resolver: lts-18.28
packages:
  - .
nix:
  # Enable Nix support
  enable: true
  # Pass environment variables, like `NIX_PATH`
  pure: false
  # Specify the Nix file to use (otherwise it uses `shell.nix` by default)
  shell-file: nix/stack-integration.nix
